### ISSUE TITLE
FusionCacheEntryOptions.IsFailSafeEnabled Ignored

### ISSUE THREAD

**Issue by EricMKaufman** [jodydonetti/ZiggyCreatures.FusionCache#45]
Hey @jodydonetti,

I don't think is a major issue, but it did trip up a unit test I was working on. In some scenarios it seems like `IsFailsSafeEnabled = false` is ignored. Here's an example.

```		
[Fact]
public void IsFailSafeEnabledIgnoredHere()
{
	using var cache = new FusionCache(new FusionCacheOptions()
	{
		DefaultEntryOptions = new FusionCacheEntryOptions()
		{
			IsFailSafeEnabled = true,
			Duration = TimeSpan.FromSeconds(1),
			FailSafeMaxDuration = TimeSpan.FromSeconds(2)
		}
	});

	const string cacheKey = "cacheKey";
	cache.Set(cacheKey, "someValue");

	var cacheItem = cache.TryGet<string>(cacheKey);
	Assert.True(cacheItem.HasValue);

	Thread.Sleep(1500);

	cacheItem = cache.TryGet<string>(cacheKey);
	Assert.True(cacheItem.HasValue);

	cacheItem = cache.TryGet<string>(cacheKey, new FusionCacheEntryOptions() { IsFailSafeEnabled = false });
	Assert.False(cacheItem.HasValue); //Fails here

	Thread.Sleep(2001);

	cacheItem = cache.TryGet<string>(cacheKey);
	Assert.False(cacheItem.HasValue);
}

[Fact]
public void IsFailSafeEnabledWorksAsExpected()
{
	using var cache = new FusionCache(new FusionCacheOptions()
	{
		DefaultEntryOptions = new FusionCacheEntryOptions()
		{
			IsFailSafeEnabled = true,
			Duration = TimeSpan.FromSeconds(1),
			FailSafeMaxDuration = TimeSpan.FromSeconds(2)
		}
	});

	const string cacheKey = "cacheKey";
	cache.Set(cacheKey, "someValue");

	var cacheItem = cache.TryGet<string>(cacheKey);
	Assert.True(cacheItem.HasValue);

	Thread.Sleep(1500);

	cacheItem = cache.TryGet<string>(cacheKey, new FusionCacheEntryOptions() { IsFailSafeEnabled = false });
	Assert.False(cacheItem.HasValue); //Is false here

	Thread.Sleep(2001);

	cacheItem = cache.TryGet<string>(cacheKey);
	Assert.False(cacheItem.HasValue);
}

[Fact]
public void IsFailSafeEnabledWorksAsExpected2()
{
	using var cache = new FusionCache(new FusionCacheOptions()
	{
		DefaultEntryOptions = new FusionCacheEntryOptions()
		{
			IsFailSafeEnabled = true,
			Duration = TimeSpan.FromSeconds(1),
			FailSafeMaxDuration = TimeSpan.FromSeconds(2)
		}
	});

	const string cacheKey = "cacheKey";
	cache.Set(cacheKey, "someValue");

	var cacheItem = cache.TryGet<string>(cacheKey);
	Assert.True(cacheItem.HasValue);

	Thread.Sleep(1500);

	cacheItem = cache.TryGet<string>(cacheKey, new FusionCacheEntryOptions());
	Assert.False(cacheItem.HasValue);

	cacheItem = cache.TryGet<string>(cacheKey, new FusionCacheEntryOptions() { IsFailSafeEnabled = false });
	Assert.False(cacheItem.HasValue); //Is false here

	Thread.Sleep(2001);

	cacheItem = cache.TryGet<string>(cacheKey);
	Assert.False(cacheItem.HasValue);
}
```

Are my assumptions incorrect on how to use `FusionCacheEntryOptions`? This was only an issue if a null `FusionCacheEntryOptions` is provided on the first `TryGet`

**Comment by jodydonetti** [comment]
Hi @EricMKaufman , thanks for using (or considering) FusionCache!
I'll try to take this code for a run as soon as possible, will update asap.

Btw, and from a very quick look it seems to me that this is what is happening:

```csharp
// This will make the entry logically expire
Thread.Sleep(1500);

// By not passing any entry options, the default will be used, which has IsFailSafeEnabled = true
// This means that when trying to get the entry, fail-safe will be activated and put again into the cache for a small
// amount of time (see FailSafeThrottleDuration), to avoid a form of cache stampede
cacheItem = cache.TryGet<string>(cacheKey);
Assert.True(cacheItem.HasValue);

// Immediately after you try to get the entry again, and that is inside the cache as described above
cacheItem = cache.TryGet<string>(cacheKey, new FusionCacheEntryOptions() { IsFailSafeEnabled = false });
Assert.False(cacheItem.HasValue); //Fails here
```

All of this is because, as said in the comment above, when fail-safe is being activated it temporarily saves the entry in the cache instead of just returning it.

Anyway I will comment better on this as soon as I have time to take a better look at it (probably this evening, Italian time).

**Comment by jodydonetti** [comment]
While I'm on the subject: if the situation is as I described, it is in fact touching on something I've been thinking about a lot for some time.

What I'm thinking about is a change in the behaviour of FusionCache, where maybe it would be better **not** to activate fail-safe in case of a simple `TryGet` or a `GetOrDefault` or in general when a factory (lambda) has not been passed, the rationale being that simply "looking for" an entry without a factory trying to refresh the data should (probably?) not activate fail-safe, and simply return what's in the cache.

But there are some considerations to be made, and I've been thinking about clearing m mind about it a little bit more, then create an issue to discuss it with the community and see what comes up.

Anyway I'll update you on your issue asap, thanks!

**Comment by jodydonetti** [comment]
Hi @EricMKaufman , I've been able to test the reasoning I've highlighted above and can confirm: what I described is what is happening.

To see for yourself the behaviour here's a way that you may find useful:

- download the repo
- go to the Playground project
- go to the `Program.cs` file
- uncomment the line `await LoggingScenario.RunAsync().ConfigureAwait(false);`
- go to the `LoggingScenario.cs` file
- go just after the line where the logging is being set up (this `var logger = UseLogger ? serviceProvider.GetService<ILogger<FusionCache>>() : null;`)
- go to the next line and paste your code from there, adding a `return;` just after that

I then commented the various `Assert` lines and the lines after your `//Fails here` comment, then run the project.
The logging scenario is configured to log at the maximun level, so that you can play around with some FusionCache calls and see the inner details of what it does.

Here is the logging output I saw:

```
[15:46:03 DBG] FUSION (O=954474e0c85f4826aad6d6f7e33da2e3 K=cacheKey): calling Set<T> FEO[LKTO=/ DUR=1s JIT=0 PR=N FS=Y FSMAX=2s FSTHR=30s FSTO=/ FHTO=/ TOFC=Y DSTO=/ DHTO=/ ABDO=N BN=Y BBO=Y]
[15:46:03 DBG] FUSION (O=954474e0c85f4826aad6d6f7e33da2e3 K=cacheKey): saving entry in memory MEO[CEXP=2s PR=N S=1] FE[FFS=N LEXP=998ms]
[15:46:03 DBG] FUSION (O=911193f568184ff7be7f0f7ead47c309 K=cacheKey): calling TryGet<T> null
[15:46:03 VRB] FUSION (O=911193f568184ff7be7f0f7ead47c309 K=cacheKey): trying to get from memory
[15:46:03 DBG] FUSION (O=911193f568184ff7be7f0f7ead47c309 K=cacheKey): memory entry found FE[FFS=N LEXP=987ms]
[15:46:03 VRB] FUSION (O=911193f568184ff7be7f0f7ead47c309 K=cacheKey): using memory entry
[15:46:03 DBG] FUSION (O=911193f568184ff7be7f0f7ead47c309 K=cacheKey): return SUCCESS
[15:46:04 DBG] FUSION (O=29ec22a9fc464e0e89c0abf4027ea97c K=cacheKey): calling TryGet<T> null
[15:46:04 VRB] FUSION (O=29ec22a9fc464e0e89c0abf4027ea97c K=cacheKey): trying to get from memory
[15:46:04 DBG] FUSION (O=29ec22a9fc464e0e89c0abf4027ea97c K=cacheKey): memory entry found (expired) FE[FFS=N LEXP=-532ms]
[15:46:04 DBG] FUSION (O=29ec22a9fc464e0e89c0abf4027ea97c K=cacheKey): saving entry in memory MEO[CEXP=2s PR=N S=1] FE[FFS=Y LEXP=30s]
[15:46:04 VRB] FUSION (O=29ec22a9fc464e0e89c0abf4027ea97c K=cacheKey): using memory entry (expired)
[15:46:04 DBG] FUSION (O=29ec22a9fc464e0e89c0abf4027ea97c K=cacheKey): return SUCCESS
[15:46:04 DBG] FUSION (O=d068ef840489403bb8e4d9a2435cc8ba K=cacheKey): calling TryGet<T> FEO[LKTO=/ DUR=30s JIT=0 PR=N FS=N FSMAX=1.00:00:00 FSTHR=30s FSTO=/ FHTO=/ TOFC=Y DSTO=/ DHTO=/ ABDO=N BN=Y BBO=Y]
[15:46:04 VRB] FUSION (O=d068ef840489403bb8e4d9a2435cc8ba K=cacheKey): trying to get from memory
[15:46:04 DBG] FUSION (O=d068ef840489403bb8e4d9a2435cc8ba K=cacheKey): memory entry found FE[FFS=Y LEXP=30s]
[15:46:04 VRB] FUSION (O=d068ef840489403bb8e4d9a2435cc8ba K=cacheKey): using memory entry
[15:46:04 DBG] FUSION (O=d068ef840489403bb8e4d9a2435cc8ba K=cacheKey): return SUCCESS
```

As you can see in the 2nd `TryGet` call it internally finds the stale entry (it is stale because of the `Thread.Sleep` call just before that) and, since no options has been passed, it uses the default one which has fail-safe enabled. Now, because of that, it proceeds to temporarily save that stale entry for reuse (with a `FailSafeThrottleDuration`, as explained in my previous comments) and so in the 3rd `TryGet` call it finds an entry, even if fail-safe has been disabled for that specific call.

These are the 2 log lines I'm talking about:

```
[15:46:04 DBG] FUSION (O=29ec22a9fc464e0e89c0abf4027ea97c K=cacheKey): memory entry found (expired) FE[FFS=N LEXP=-532ms]
[15:46:04 DBG] FUSION (O=29ec22a9fc464e0e89c0abf4027ea97c K=cacheKey): saving entry in memory MEO[CEXP=2s PR=N S=1] FE[FFS=Y LEXP=30s]
```

I hope to have clarified the internal behaviour you were interested in, but let me know.

**Comment by jodydonetti** [comment]
Hi @EricMKaufman , have you been able to take a look at my answer?
I'll close this issue for now, but if you feel like it just let me know and we can continue the conversation.
