### ISSUE TITLE
ZiggyCreatures.FusionCache.Backplane.Memory Seems to Prevent Cache From Being Used

### ISSUE THREAD

**Issue by bbrandt** [jodydonetti/ZiggyCreatures.FusionCache#46]
I had tried out ZiggyCreatures.FusionCache.Backplane.Memory for local development with a single instance.  Maybe I didn't set it up right, but if I set a breakpoint in events for cache.Events.Set and either cache.Events.Remove or cache.Events.Memory.Eviction (sorry, I don't remember which it was hitting), then each time a cache value was set, it was immediately removed.  Effectively, the cache was never used and the factory was always called.  

After I removed this line, then everything worked fine and dandy:
`services.AddFusionCacheMemoryBackplane();`

I didn't really have any good reason for using it for local dev and am fine without it, so I'm good with closing this issue immediately if you like.

**Comment by jodydonetti** [comment]
Hi @bbrandt , thanks of using FusionCache!

In general the memory implementation of the backplane should only be used for local tests, and with multiple nodes, otherwise it would do nothing.

Having said that, it should not in fact keep erasing entries with a single node, since that node would be the source of the changes, and should not be notified.

Do you have a minimal piece of code that shows the effect you are describing? I'll be happy to take a look at it, but without that I have FusionCache backplane tests passing and I don't know where to start from.

**Comment by bbrandt** [comment]
Thank you for the reply.  Closing for now.
