### ISSUE TITLE
Bad deserialization with System.Text.Json

### ISSUE THREAD

**Issue by Paulskit** [jodydonetti/ZiggyCreatures.FusionCache#5]
Thank you so much for the library. I'm trying to use it on my project and faced an issue when using default .net 3.1 json serializer and `IDistributedCache` backed by Redis. 

Steps to reproduce:
1) Add `services.AddFusionCacheSystemTextJsonSerializer`
2) Create a model 
```csharp
class LastModified
  {
    public DateTime Date { get; set; }
  }
```

3) Try get the data
```csharp
await _cache.GetOrSetAsync<LastModified>(_cacheKey, ReadFromDb, token: token);
```

You'll notice a warning written to the console:
![image](https://user-images.githubusercontent.com/9947675/109306978-a4a22400-7848-11eb-90d3-c4f4585f1ef4.png)

Here is what is read from the Redis
![image](https://user-images.githubusercontent.com/9947675/109307140-da470d00-7848-11eb-8c93-41964af01231.png)
Notice the `Metadata` object. It doesn't have a parameterless constructor and that's what exception is about.

**Comment by jodydonetti** [comment]
Hi @Paulskit , thanks for giving FusionCache a try!
I saw this issue only now cause no mail notification from github 🤷
Let me check it locally, I'll update you asap.

**Comment by jodydonetti** [comment]
Hi @Paulskit you were right about a missing parameterless ctor, good catch 👍

I think I haven't catched it because after some time I used mostly the Newtonsoft one (which does not suffer from the same limitation).

To avoid problems like these in the future I also changed the multi-level tests so that they run automatically on both serializers (see [here](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/blob/main/tests/ZiggyCreatures.FusionCache.Tests/MultiLevelTests.cs)) instead of running only with the Newtonsoft one.

I've now fixed the bug and release a new **v0.1.2** of the 3 main packages: they will be available as soon as their validation finishes, so you'll then have to just update the packages on your side.

Thanks for the issue, and let me know if everything will be fine.

**Comment by Paulskit** [comment]
Wow, that was fast! Thank you, I'll give it another go, really appreciate your work done on this library and a level of commitment. That's very impressive.

**Comment by jodydonetti** [comment]
Thanks, appreciate that!

**Comment by Paulskit** [comment]
It's fixed for me, thank you.

**Comment by jodydonetti** [comment]
Awesome, thanks for checking it.
