### ISSUE TITLE
GetOrSet, but do not cache null values from factory.

### ISSUE THREAD

**Issue by Cephei** [jodydonetti/ZiggyCreatures.FusionCache#51]
I've read through most documentation I can find and a good amount of discussions on here in the issues. Perhaps I'm not thinking through my scenario clearly, but I feel like GetOrSet should have a option of some kind to ignore null values and just return null.

In a previous issue, someone had mentioned something along the lines of GetOrSetOrDefault ... which may be what I'm thinking.
The issue I see is this:
```
return _cache.GetOrSet(
    "key",
    ctx => {
        _repository.Get(...);
    },
    opt => { ... }
);
```

If `_repository.Get(..)` returns `null`, I don't want to cache this. My only option is to throw an exception from within the factory func. Is this the intended design?

I could, of course, break this down into separate `TryGetAsync`, followed by a `SetAsync`.

**Comment by jasenf** [comment]
Agreed.   Null should be able to be stored as a cache value automatically if it isn't already.

**Comment by Cephei** [comment]
@jasenf From what I see, FusionCache will cache null results by default from factory methods. For non-nullable types, this makes sense. For example, take a factory that returns an `int` and the result is 0. FusionCache cannot distinguish between a default value from an actual result. But if the factory is returning a nullable type, do most people really want to cache nulls?

And if not, should we just throw exceptions from the factory and handle this outside?

**Comment by Cephei** [comment]
That all sounds reasonable. I've changed the code to use TryGet/Set and I think it reads a bit clearer now anyhow. Perhaps for this use case it makes more sense than using GetOrSet.

**Comment by jodydonetti** [comment]
Hi @Cephei and thanks for using FusionCache.

You are correct, `null` is normally cacheable because, as @jasenf also pointed out, that is a reasonable behaviour. For more on this you can check this [post](https://nickcraver.com/blog/2019/08/06/stack-overflow-how-we-do-app-caching/) by Nick Craver where he says this:

> It also allows the caching of a null value and makes that handling not special-cased. In other words, you can tell the difference between “It’s not cached” and “We looked it up. It was null. We cached that null. STOP ASKING!”

This alone in the vast majority of situations will avoid a kind of vulnerability where people may bombard your database and maybe take it down because they are asking for product/123 and that product does not exist, since not caching `null` would mean going to the database each and every time, as Nick also pointed out in his post.

I would also discourage the usage of separate `TryGet` + `Set` because not using a single atomic method (eg: `GetOrSet`) you may end up experiencing phenomena like [Cache Stampede](https://en.wikipedia.org/wiki/Cache_stampede) or [Thundering Herd](https://en.wikipedia.org/wiki/Thundering_herd_problem), which again can tear down your database.

What I usually do in case I want to cache `null` for less time is I use [adaptive caching](https://github.com/jodydonetti/ZiggyCreatures.FusionCache/blob/main/docs/AdaptiveCaching.md) and set a low duration in case of `null` (eg: a product is cached for `5min` but `null` is cached for `10sec`).

Finally, if you really really want to NOT cache `null` (knowing that multiple sequential requests will go to the database every single time), what I would do is use adaptive caching as I said above and set a duration of, like `10ms`: doing this will at least let you avoid the Cache Stampede problem I outlined above since 100 concurrent requests for the same data will, at least, be executed in asynchronized fashion and not go each to the database, something you will not get with a `TryGet` followed by a `Set`.

If you need something more let me know.

Hope this helps!

**Comment by Cephei** [comment]
Very insightful. I sincerely appreciate the well articulated responses here guys. 🍻
